### ISSUE TITLE
Regarding the backbone network 

### ISSUE THREAD

**Issue by leebebeto** [dnap512/SelfReg#1]
Thanks for the wonderful work

One thing I want to ask is the backbone network of your work. 
The paper says that you used ResNet18 for the backbone network.
However, in DomainBed, all experiments are conducted with ResNet50. 
You used the same results from DomainBed paper for other baselines (which used ResNet50) in your paper but your method is conducted with ResNet18. 
Can you clarify the experiment setting regarding such issue? 

Thanks, in advance

**Comment by dnap512** [comment]
Hi, @leebebeto 

Thank you for your interest in our work.
In DomainBed, we used ResNet50 for our experiments.
As you know, our SelfReg is not limited to specific backbone.

Thank you.
