### ISSUE TITLE
About a code problem

### ISSUE THREAD

**Issue by ToxicDoubleH** [dnap512/SelfReg#3]
Hello, when I read your code, there is problem.
In your code, SelfReg-main/codes/utils.py line 224-226
`if is_self_reg:
    output, feat = model.extract_features(x)
    proj = model.projection(feat)
elif is_positive_pair:
    output, feat = model.extract_features(x1)
    output2, feat2 = model.extract_features(x2)`
I want to know the function about elif, what the is_positive_pair is and x1, x2 is what,
Wish your respond.

**Comment by dnap512** [comment]
Hi, @ToxicDoubleH !

I'm sorry for the confusion.
Those codes are traces of what I was researching in the past. ( is_positive_pair condition )
I thought I deleted it, but it's still there. :(
I'll clean it up properly when I clean up the code later.

Thank you for your interesting in our research.

**Comment by ToxicDoubleH** [comment]
Thank you for your respond! Sorry for 2 days later.
Yours a nice job!
And there is an other question. Your batchsize is 128, and PACS has only 7 classes, each class may have 18 imges. So if a dataset does not have so many images for a single class. Does it works? You say that negative pairs is damage, can your work be worked with negative pairs, such as triplet loss?
Wish your respond.

**Comment by dnap512** [comment]
Dear @ToxicDoubleH

As you know, SelfReg doesn't use negative pairs.
I think SelfReg will work, if you want to use Selfreg with negative pairs.
But then, there may not be much difference between SelfReg and triple loss.

Thank you.

**Comment by ToxicDoubleH** [comment]
Thanks for your respond. I got it.
