### ISSUE TITLE
A question about the domainbed_code

### ISSUE THREAD

**Issue by BX-xb** [dnap512/SelfReg#5]
Hi,  I have a question, in https://github.com/dnap512/SelfReg/blob/05d9777139309f2495bd1e9394d73f4e56402744/domainbed_code/algorithms.py#L75.
if the optimizer optimizes only the parameters of self.featurizer and self.classifier, and self.cdpl seems not to be trained.

**Comment by dnap512** [comment]
Hi @BX-xb!

Please refer to https://github.com/facebookresearch/DomainBed/issues/62.

Thank you!
