### ISSUE TITLE
T-SNE Results 

### ISSUE THREAD

**Issue by Smart-Robotics-Scientist** [dnap512/SelfReg#7]
Hi,

I wonder how to get the T-SNE Results?

**Comment by dnap512** [comment]
Hi, @Smart-Robotics-Scientist.

1. For example, if the PACS dataset is used, there are a total of 4 domains and a total of 4 models to be used for testing.
2. Extract features for each target domain. (at this https://github.com/dnap512/SelfReg/blob/43bd84b93cfb0832229d4a324ac763d441c28efe/codes/model/resnet18_selfreg.py#L255)
3. All these features are used at once and visualized with t-SNE.

Thank you.
